/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7080709a-d653-44c5-ad16-c02f9d693618",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iQ9Lct78n",
    "aws_user_pools_web_client_id": "3himmdpsphbn2eh8oiogq0498t",
    "oauth": {}
};


export default awsmobile;
