/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9e875a39-5200-4b79-b2e4-e71363541640",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7YBfh4asT",
    "aws_user_pools_web_client_id": "13lduc85ed8uioc787lfghki6c",
    "oauth": {}
};


export default awsmobile;
